AparmentBillManagementMVC/Controllers/ApartmentController.cs
using Bussiness.Abstract;
using Core.Utilities;
using Entity.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AparmentBillManagementMVC.Controllers
{
    [Authorize(Roles = "manager")]
    public class ApartmentController : Controller
    {
        private readonly IApartmentService apartmentService;
        public ApartmentController(IApartmentService apartmentService)
        {
            this.apartmentService = apartmentService;
        }
        public IActionResult Index()
        {

            int apartmentComplexId = int.Parse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value);
            var result = apartmentService.GetApartmentVMsByComplexId(apartmentComplexId);
            return View(result.Data);
        }

        public IActionResult Apartment()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Apartment([FromForm] ApartmentDTO apartmentDTO)
        {
            var ApartmentComplexIdResult = GetApartmentComplexIdViaClaims();
            if (ApartmentComplexIdResult.Success == false)
            {
                TempData["message"] = "An error occured. Please re login to website.";
                return View();
            }

            if (ModelState.IsValid)
            {
                apartmentDTO.ApartmentComplexId = ApartmentComplexIdResult.Data;
                var result = apartmentService.Add(apartmentDTO);
                TempData["message"] = result.Message;
                if (result.Success == true)
                {
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        public IActionResult Delete([FromRoute] int id)
        {
            var result = apartmentService.DeleteById(id);
            TempData["message"] = result.Message;
            return RedirectToAction("Index");
        }

        public IActionResult Update([FromRoute] int id)
        {
            var apartmentForUpdate = apartmentService.GetById(id).Data;
            return View(apartmentForUpdate);
        }

        [HttpPost]
        public IActionResult Update([FromForm] ApartmentDTO apartmentDTO)
        {
            if (ModelState.IsValid)
            {
                var result = apartmentService.Update(apartmentDTO);
                TempData["message"] = result.Message;
                return RedirectToAction("Index");
            }
            return View();
        }


        [HttpPost]
        public PartialViewResult ApartmentsList(string? blockName, string? nameFilter, bool onlyHasDebt)
        {
            var getApartmentComplexIdResult = GetApartmentComplexIdViaClaims();
            if (getApartmentComplexIdResult.Success == false)
            {
                TempData["message"] = "An error occured. Please re login to website.";
                return PartialView(null);
            }

            int apartmentComplexId = getApartmentComplexIdResult.Data;

            if (blockName == "all")
                blockName = null;
            var result = apartmentService.GetApartmentVMsByComplexId(apartmentComplexId, blockName, nameFilter, onlyHasDebt);
            return PartialView(result.Data);
        }

        public DataResult<int> GetApartmentComplexIdViaClaims()
        {
            try
            {
                int apartmentComplexId = int.Parse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value);
                return new DataResult<int>(true, "Complex Id fetched succesfully", apartmentComplexId);
            }
            catch
            {
                return new DataResult<int>(false, "Complex Id couldn't fetched", -1);
            }

        }


    }
}

AparmentBillManagementMVC/Controllers/BillController.cs
using AutoMapper;
using Bussiness.Abstract;
using Core.Utilities;
using Entity;
using Entity.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AparmentBillManagementMVC.Controllers
{
    [Authorize(Roles = "manager")]
    public class BillController : Controller
    {
        private readonly IBillService billService;
        private readonly IMapper mapper;

        public BillController(IBillService billService, IMapper mapper)
        {
            this.billService = billService;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            var idResult = GetApartmentComplexIdViaClaims();
            if (idResult.Success == false)
            {
                TempData["message"] = "An error occured. Please re login to website.";
                return View();
            }
            ViewBag.apartmentComplexId = idResult.Data;
            var billList = billService.GetListWithRelatedData(apartmentComplexId: idResult.Data, page: 0).Data;
            return View(billList);
        }

        public PartialViewResult BillsPartialList(int apartmentComplexId, int billPage)
        {
            var billList = billService.GetListWithRelatedData(apartmentComplexId: apartmentComplexId, page: billPage - 1).Data;
            return PartialView(billList);
        }

        public IActionResult Bill(int apartmentId, string? tenantName)
        {
            BillDTO billDTO = new();
            billDTO.ApartmentId = apartmentId;
            ViewData["tenantName"] = tenantName;
            return View(billDTO);
        }

        [HttpPost]
        public IActionResult Bill([FromForm] BillDTO billDTO)
        {
            if (ModelState.IsValid)
            {
                var result = billService.Add(billDTO);
                TempData["message"] = result.Message;
                return RedirectToAction("Index");
            }
            return View(billDTO);
        }

        public IActionResult Delete([FromRoute] int id)
        {
            var result = billService.DeleteById(id);
            TempData["message"] = result.Message;
            return RedirectToAction("Index");
        }


        public IActionResult Update([FromRoute] int id)
        {
            var result = billService.GetById(id);
            var billDTO = mapper.Map<Bill, BillDTO>(result.Data);
            return View(billDTO);
        }

        [HttpPost]
        public IActionResult Update([FromForm] BillDTO billDTO)
        {
            if (ModelState.IsValid)
            {
                var result = billService.Update(billDTO);
                TempData["message"] = result.Message;
                return RedirectToAction("Index");
            }
            return View(billDTO);

        }

        public DataResult<int> GetApartmentComplexIdViaClaims()
        {
            try
            {
                int apartmentComplexId = int.Parse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value);
                return new DataResult<int>(true, "Complex Id fetched succesfully", apartmentComplexId);
            }
            catch
            {
                return new DataResult<int>(false, "Complex Id couldn't fetched", -1);
            }

        }
    }
}

AparmentBillManagementMVC/Controllers/MessageController.cs
using AutoMapper;
using Bussiness.Abstract;
using Core.Utilities;
using Entity.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AparmentBillManagementMVC.Controllers
{
    [Authorize(Roles = "manager")]
    public class MessageController : Controller
    {
        private readonly IMessageService messageService;
        private readonly IChatRoomService chatRoomService;
        private readonly IMapper mapper;
        public MessageController(IMessageService messageService, IChatRoomService chatRoomService, IMapper mapper)
        {
            this.messageService = messageService;
            this.chatRoomService = chatRoomService;
            this.mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index(int? tenantId)
        {
            int apartmentComplexId;
            var getIdViaClaim = int.TryParse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value, out apartmentComplexId);
            if (!getIdViaClaim)
            {
                TempData["message"] = "An error occured. Please re login to website.";
                return RedirectToAction("Login", "Auth");
            }

            if (tenantId != null)
            {
                var chatRoomDTO = new ChatRoomDTO
                {
                    TenantId = (int)tenantId,
                    LastSeenMessageId = null,
                };
                var chatRoom = chatRoomService.Add(chatRoomDTO);

                ViewBag.chatRoomId = chatRoom.Data.Id;
            }


            var result = chatRoomService.GetChatRoomVMs(apartmentComplexId).Data;
            if (tenantId != null)
            {
                var cr = result.Find(x => x.TenantId == tenantId);
                result.Remove(cr);
                result.Insert(0, cr);
            }

            return View(result);
        }

        [HttpPost]
        public PartialViewResult MessageList(int chatRoomId)
        {
            var result = messageService.GetAllMessagesOfConversation(chatRoomId);
            if (result.Data.Count != 0)
                chatRoomService.UpdateWithMessageDTO(result.Data.Last());
            ViewBag.chatRoomId = chatRoomId;
            return PartialView(result.Data);
        }

        [HttpPost]
        public PartialViewResult MessageItem(MessageDTO messageDTO)
        {
            // TODO: if messageDTOFromDBResult is not success, return error message


            messageDTO.MessageTime = DateTime.Now;
            var messageDTOFromDBResult = messageService.Add(messageDTO);
            if (!messageDTOFromDBResult.Success)
            {
                return PartialView(null);
            }
            var result = chatRoomService.UpdateWithMessageDTO(messageDTOFromDBResult.Data);

            return PartialView(messageDTOFromDBResult.Data);
        }

        [HttpGet]
        public PartialViewResult MessageItem(int chatRoomId)
        {
            var result = messageService.GetNewMessagesOfConversation(chatRoomId);
            if (result.Data.Count == 0)
                return PartialView(null);
            chatRoomService.UpdateWithMessageDTO(result.Data.First());
            ViewBag.isMessageNew = true;
            return PartialView(result.Data.First());
        }

        [HttpDelete]
        public Result Delete(int chatRoomId, int messageId)
        {
            var updateChatRoom = chatRoomService.UpdateLastSeenMessageIdWithNewMax(chatRoomId, messageId);

            var result = messageService.DeleteById(messageId);
            return result;
        }

        [HttpGet]
        public int GetUnreadMessageCount(int chatRoomId, int lastSeenMessageId)
        {

            var result = messageService.GetUnreadMessageCount(chatRoomId, lastSeenMessageId);
            return result;
        }

        [HttpGet]
        public int GetTotalUnreadMessageCount()
        {
            int apartmentComplexId = 0;
            bool parsing = int.TryParse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value, out apartmentComplexId);
            if (parsing is false)
            {
                return 0;
            }
            var result = messageService.GetUnreadMessageCountByApartmentComplexId(apartmentComplexId);
            return result;
        }

    }
}

AparmentBillManagementMVC/Controllers/TenantController.cs
using Bussiness.Abstract;
using Core.Utilities;
using Entity.DTOs;
using Entity.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AparmentBillManagementMVC.Controllers
{
    [Authorize(Roles = "manager")]
    public class TenantController : Controller
    {
        private readonly ITenantService tenantService;

        public TenantController(ITenantService tenantService)
        {
            this.tenantService = tenantService;
        }

        public IActionResult Index()
        {
            var idResult = GetApartmentComplexIdViaClaims();
            if (idResult.Success == false)
            {
                TempData["message"] = "Something went wrong. Please re login to website.";
                return View(new List<TenantVM>());
            }

            var model = tenantService.GetTenantVMs(apartmentComplexId: idResult.Data).Data;
            return View(model);
        }

        public IActionResult Tenant([FromQuery] int apartmentId)
        {
            TenantDTO tenantDTO = new TenantDTO();
            tenantDTO.ApartmentId = apartmentId;
            return View(tenantDTO);
        }

        [HttpPost]
        public IActionResult Tenant([FromForm] TenantDTO tenantDTO)
        {

            if (ModelState.IsValid)
            {
                var result = tenantService.Add(tenantDTO);
                TempData["message"] = result.Message;
                if (result.Success)
                {
                    return RedirectToAction("Index");
                }

            }
            return View(tenantDTO);
        }

        public IActionResult Delete(int id)
        {
            var result = tenantService.DeleteById(id);
            TempData["message"] = result.Message;
            return RedirectToAction("Index");
        }

        public IActionResult Update([FromRoute] int id)
        {
            var model = tenantService.GetAsDTOById(id);
            if (model == null)
            {
                TempData["message"] = model.Message;
            }
            return View(model.Data);
        }

        [HttpPost]
        public IActionResult Update(TenantDTO tenantDTO)
        {
            if (ModelState.IsValid)
            {
                var result = tenantService.Update(tenantDTO);
                TempData["message"] = result.Message;
                if (result.Success)
                    return RedirectToAction("Index");
            }
            return View(tenantDTO);
        }

        [HttpPost]
        public PartialViewResult TenantsList(string? blockName, string? nameFilter, bool onlyHasDebt)
        {
            var idResult = GetApartmentComplexIdViaClaims();
            if (idResult.Success == false)
            {
                TempData["message"] = "Something went wrong. Please re login to website.";
                return PartialView(new List<TenantVM>());
            }

            if (blockName == "all")
            {
                blockName = null;
            }
            var model = tenantService.GetTenantVMs(idResult.Data, blockName, nameFilter, onlyHasDebt);
            return PartialView(model.Data);
        }

        public DataResult<int> GetApartmentComplexIdViaClaims()
        {
            try
            {
                int apartmentComplexId = int.Parse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value);
                return new DataResult<int>(true, "Complex Id fetched succesfully", apartmentComplexId);
            }
            catch
            {
                return new DataResult<int>(false, "Complex Id couldn't fetched", -1);
            }

        }
    }
}

AparmentBillManagementMVC/Views/Apartment/Apartment.cshtml
@model Entity.Apartment

@if (TempData["message"] is not null)
{
    <div class="alert alert-info">@TempData["message"]</div>
}

<form method="Post" asp-controller="Apartment" >

    <h5>New Apartment Form</h5>
    <form-group>
        <div>
        <label asp-for="Floor"></label>
            <input asp-for="Floor" min="0" placeholder="0" required />
        </div>
        <span asp-validation-for="Floor" class="text-danger"></span>
    </form-group>
    <form-group>
        <div>
        <label asp-for="Number"></label>
            <input asp-for="Number" min="0" placeholder="0" size="100" required />
        </div>
        <span asp-validation-for="Number" class="text-danger"></span>

    </form-group>

    <form-group>
        <div>

        <label asp-for="BlockName"></label>
            <input asp-for="BlockName" placeholder="A - B..." required />
        </div>
        <span asp-validation-for="BlockName" class="text-danger"></span>
    </form-group>

    <form-group>
        <div>
        <label asp-for="Type"></label>
            <input asp-for="Type" placeholder="(2+1) etc." required />
        </div>
        <span asp-validation-for="Type" class="text-danger"></span>

    </form-group>


    <input type="submit" value="Add Apartment" asp-action="Apartment" />
    

</form>

AparmentBillManagementMVC/Views/Apartment/ApartmentsList.cshtml
@model List<ApartmentVM>

<style>
    .rotate {
        transform: rotate(90deg);
        /* Safari */
        -webkit-transform: rotate(90deg);
        /* Firefox */
        -moz-transform: rotate(90deg);
        /* IE */
        -ms-transform: rotate(90deg);
        /* Opera */
        -o-transform: rotate(90deg);
        /* Internet Explorer */
        filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
        position: absolute;
        right: 0;
        bottom: 40px;
    }
</style>



@if (Model is not null)
{
    <div class="row justify-content-center">
        @if (Model.Count < 1)
        {
            <p class="alert alert-danger m-3 px-2"> There is no apartment</p>
        }
        @foreach (ApartmentVM item in Model)
        {

            <div class="card my-3 mx-3 col-md-6 col-lg-4  col-xl-2 apartmentCard" style="width: 18rem;">
                <div class="card-body d-flex flex-column justify-content-between">
                    <div>
                        <h2 class="card-title">@item.Apartment.BlockName - @item.Apartment.Number</h2>
                        @if (String.IsNullOrEmpty(item.TenantName) == false)
                        {
                            <h6 class="card-subtitle mb-2 text-muted">@item.TenantName</h6>
                        }
                        else
                        {
                            <div class="d-flex justify-content-between align-items-baseline">
                                <h6 class="card-subtitle mb-2 text-success ">No Tenant</h6>
                                <a class="btn btn-outline-success  p-1" asp-controller="Tenant" asp-action="Tenant" asp-route-apartmentId="@item.Apartment.Id"><i class="fa fa-plus"></i> Add Tenant</a>
                            </div>
                        }
                        <p>Floor:  @item.Apartment.Floor</p>
                        <p>Type:  @item.Apartment.Type.ToString()</p>
                        @if (item.DebtAmount > 0)
                        {
                            <p>Debt:  <big class="card-text text-danger">@string.Format("{0:C}",item.DebtAmount)</big></p>
                        }
                        else if (item.DebtAmount == 0)
                        {
                            <p>Debt:  <big class="card-text text-success">@string.Format("{0:C}",item.DebtAmount)</big></p>
                        }

                    </div>
                    <div style="margin-right:40px; bottom:20px">
                        @if(item.TenantId != -1)
                        {
                            <a class="btn btn-success mb-3 w-100" asp-controller="Message" asp-action="Index" asp-route-tenantId="@item.TenantId">
                            <i class="fa fa-envelope"></i> Send Message
                            </a>
                        }
                        else
                        {
                            <a class="btn btn-success mb-3 w-100 disabled" asp-controller="Message" asp-action="Index" asp-route-tenantId="@item.TenantId">
                                <i class="fa fa-envelope"></i> Send Message
                            </a>
                        }

                        <a class="btn btn-warning text-white w-100" asp-controller="Apartment" asp-action="Update" asp-route-id="@item.Apartment.Id">
                            <i class="fa fa-pencil"></i>  Update Apartment
                        </a>
                        @if (String.IsNullOrEmpty(item.TenantName) == false)
                        {
                            <a class="btn btn-outline-info rotate" asp-controller="Bill" asp-action="Bill" asp-route-apartmentId="@item.Apartment.Id" asp-route-tenantName="@item.TenantName">Add Bill</a>
                        }
                        else
                        {
                            <a class="btn btn-outline-info rotate" onclick="addBillAlert()">Add Bill</a>
                        }

                    </div>
                </div>
            </div>
        }

    </div>

}

AparmentBillManagementMVC/Views/Apartment/Index.cshtml
@model List<ApartmentVM>

@{
    string? message = TempData["message"] as string ?? null;
    List<string> blocks = Model.DistinctBy(a => a.Apartment.BlockName).Select(a => a.Apartment.BlockName).Order().ToList();
}


<h2 class="d-flex justify-content-center mb-4">Apartments List</h2>

<div class="d-flex flex-wrap justify-content-between mb-2 gap-3">
    <div id="blockRadioBtns" class="btn-group  " role="group" aria-label="Basic radio toggle button group">
        <input type="radio" class="btn-check" name="btnradio" id="all" autocomplete="off" checked onclick="filterApartments()">
        <label class="btn btn-outline-primary" for="all">All Blocks</label>

        @foreach (string blockName in blocks)
        {
            <input type="radio" class="btn-check" name="btnradio" id="@blockName" autocomplete="off" onclick="filterApartments()">
            <label class="btn btn-outline-primary" for="@blockName">@blockName</label>
        }
    </div>
    <div class="flex-fill">
        <input id="filter" class="w-100 form-control" placeholder="Search  by tenant name" aria-label="Search" onkeyup="filterApartments()">
    </div>
    <div class="" style="background-color:rgba(255,255,255,0.4)">
        <input type="checkbox" class="btn-check" id="debtCheck" autocomplete="off" onchange="filterApartments()">
        <label class="btn btn-outline-primary" for="debtCheck"><i id="debtCheckIcon" class="fa fa-close"></i> Only Has Debt</label><br>
    </div>

    <a class="btn btn-outline-primary" style="background-color:rgba(255,255,255,0.4)" asp-action="Apartment">Add Apartment</a>
</div>
<div id="apartmentList">
    @await Html.PartialAsync("ApartmentsList")
</div>

@section Scripts{
<script>
    $(document).ready(function () {
        let message = "@message";
        if (message != null && message != "") {
            Swal.fire("Info", message);
        }
    });


    function filterApartments() {
        let blockName = $("#blockRadioBtns input[type='radio']:checked").attr("id");
        let filter = $("#filter").val();
        let debtCheck = $("#debtCheck").prop("checked");
        $.post("/Apartment/ApartmentsList?blockName=" + blockName + "&nameFilter=" + filter + "&onlyHasDebt=" + debtCheck).then(
            function (result) {
                $("#apartmentList").html(result);
            }
        );
        if (debtCheck) {
            $("#debtCheckIcon").removeClass("fa-close");
            $("#debtCheckIcon").addClass("fa-check");
        } else {
            $("#debtCheckIcon").removeClass("fa-check");
            $("#debtCheckIcon").addClass("fa-close");
        }
    }

</script>
}

AparmentBillManagementMVC/Views/Apartment/Update.cshtml
@model Entity.Apartment

<form method="Post" asp-controller="Apartment">

    <h5>Apartment Form</h5>
    <form-group>
        <input asp-for="Id" hidden/>
        <input asp-for="ApartmentComplexId" hidden/>
        <div>
            <label asp-for="Floor"></label>
            <input asp-for="Floor" min="0" placeholder="0" required />
        </div>
        <span asp-validation-for="Floor" class="text-danger"></span>
    </form-group>
    <form-group>
        <div>
            <label asp-for="Number"></label>
            <input asp-for="Number" min="0" placeholder="0" size="100" required />
        </div>
        <span asp-validation-for="Number" class="text-danger"></span>

    </form-group>

    <form-group>
        <div>

            <label asp-for="BlockName"></label>
            <input asp-for="BlockName" placeholder="A - B..." required />
        </div>
        <span asp-validation-for="BlockName" class="text-danger"></span>
    </form-group>

    <form-group>
        <div>
            <label asp-for="Type"></label>
            <input asp-for="Type" placeholder="(2+1) etc." required />
        </div>
        <span asp-validation-for="Type" class="text-danger"></span>

    </form-group>

        <input type="submit" value="Update Apartment" asp-action="Update" />



</form>