AparmentBillManagementMVC/Controllers/AuthController.cs
using Bussiness.Abstract;
using Entity;
using Entity.DTOs;
using Entity.enums;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AparmentBillManagementMVC.Controllers
{
    public class AuthController : Controller
    {
        private readonly ITenantService tenantService;
        private readonly IManagerService managerService;

        public AuthController(ITenantService tenantService, IManagerService managerService)
        {
            this.tenantService = tenantService;
            this.managerService = managerService;

            InitializeDb();
        }
        public async void InitializeDb(){
            //we are making this request to make db online.
            try
            {
            tenantService.GetByMail("test@test.com");
            }
            catch (System.Exception)
            {
                Console.WriteLine("An error occured while initializing db.");
            }
        }

        public IActionResult Index()
        {
            String? mail = Request.Cookies["userMailCookie"];
            if (mail != null)
            {
                String password = Request.Cookies["userPasswordCookie"] ?? "";
                String userType = Request.Cookies["userTypeCookie"] ?? "";
                UserType type = (userType == "tenant") ? UserType.tenant : UserType.manager;

                LoginDTO user = new LoginDTO { Mail = mail, Password = password, UserType = type, RememberMe = true };
                return View(user);
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginDTO loginDTO)
        {
            CredentialsCookieOperations(loginDTO);

            dynamic userResult = (loginDTO.UserType == UserType.manager) ?
                managerService.Login(loginDTO) :
                tenantService.Login(loginDTO);

            if (userResult.Success == false)
            {
                string message = userResult.Message;
                string error = "";
                var errorResult = userResult.Message.Split("{error}");
                if ((errorResult.Length > 1))
                {
                    message = errorResult[0];
                    error = errorResult[1];
                }
                ViewBag.errorMSG = message;
                ViewBag.error = error;
                ModelState.AddModelError("Password", message);
                return View(loginDTO);
            }


            string role = (loginDTO.UserType == UserType.tenant) ? "tenant" : "manager";
            string nameIdentifier = (loginDTO.UserType == UserType.tenant) ? userResult.Data.Id.ToString() : userResult.Data.ApartmentComplexId.ToString();


            var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.NameIdentifier, nameIdentifier),
                        new Claim(ClaimTypes.Email, loginDTO.Mail),
                       new Claim(ClaimTypes.Role, role),
                    };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties();

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                                          new ClaimsPrincipal(claimsIdentity),
                                          authProperties);



            if (loginDTO.UserType == UserType.manager)
                return RedirectToAction("Index", "Apartment");
            else
                return RedirectToAction("Index", "Home", new { area = "TenantUser" });

        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index");
        }

        public IActionResult Register()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Register(Manager manager)
        {

            if (ModelState.IsValid)
            {
                var result = managerService.AddManagerWithApartmentComplex(manager);
                if (result.Success)
                {
                    TempData["message"] = "Registration successful. You can login now.";
                    return RedirectToAction("Index");
                }

                ViewBag.error = result.Message;
            }

            return View(manager);
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        public IActionResult LandingPage()
        {
            return View();
        }

        private void CredentialsCookieOperations(LoginDTO loginDTO)
        {
            if (loginDTO.RememberMe)
            {
                CookieOptions options = new CookieOptions();
                options.Expires = DateTime.Now.AddDays(5);
                Response.Cookies.Append("userMailCookie", loginDTO.Mail, options);
                Response.Cookies.Append("userPasswordCookie", loginDTO.Password, options);
                Response.Cookies.Append("userTypeCookie", loginDTO.UserType.ToString(), options);
            }
            else
            {
                Response.Cookies.Delete("userMailCookie");
                Response.Cookies.Delete("userPasswordCookie");
                Response.Cookies.Delete("userTypeCookie");
            }
        }

        public async Task<IActionResult> ManagerTestLogin()
        {

            var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.NameIdentifier, "1"),//ApartmentComplexId
                        new Claim(ClaimTypes.Email, "test@test.com"),
                       new Claim(ClaimTypes.Role, "manager"),
                    };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties();

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                                          new ClaimsPrincipal(claimsIdentity),
                                          authProperties);

            return RedirectToAction("Index", "Apartment");
        }

        public async Task<IActionResult> TenantTestLogin()
        {


            var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.NameIdentifier, "1"),//tenantId
                        new Claim(ClaimTypes.Email, "test@test.com"),
                       new Claim(ClaimTypes.Role, "tenant"),
                    };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties();

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                                          new ClaimsPrincipal(claimsIdentity),
                                          authProperties);

            return RedirectToAction("Index", "Home", new { area = "TenantUser" });
        }

        public bool IsAuthenticated()
        {
            return User.Identity.IsAuthenticated;
        }
    }
}

AparmentBillManagementMVC/Controllers/BillController.cs
using AutoMapper;
using Bussiness.Abstract;
using Core.Utilities;
using Entity;
using Entity.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AparmentBillManagementMVC.Controllers
{
    [Authorize(Roles = "manager")]
    public class BillController : Controller
    {
        private readonly IBillService billService;
        private readonly IMapper mapper;

        public BillController(IBillService billService, IMapper mapper)
        {
            this.billService = billService;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            var idResult = GetApartmentComplexIdViaClaims();
            if (idResult.Success == false)
            {
                TempData["message"] = "An error occured. Please re login to website.";
                return View();
            }
            ViewBag.apartmentComplexId = idResult.Data;
            var billList = billService.GetListWithRelatedData(apartmentComplexId: idResult.Data, page: 0).Data;
            return View(billList);
        }

        public PartialViewResult BillsPartialList(int apartmentComplexId, int billPage)
        {
            var billList = billService.GetListWithRelatedData(apartmentComplexId: apartmentComplexId, page: billPage - 1).Data;
            return PartialView(billList);
        }

        public IActionResult Bill(int apartmentId, string? tenantName)
        {
            BillDTO billDTO = new();
            billDTO.ApartmentId = apartmentId;
            ViewData["tenantName"] = tenantName;
            return View(billDTO);
        }

        [HttpPost]
        public IActionResult Bill([FromForm] BillDTO billDTO)
        {
            if (ModelState.IsValid)
            {
                var result = billService.Add(billDTO);
                TempData["message"] = result.Message;
                return RedirectToAction("Index");
            }
            return View(billDTO);
        }

        public IActionResult Delete([FromRoute] int id)
        {
            var result = billService.DeleteById(id);
            TempData["message"] = result.Message;
            return RedirectToAction("Index");
        }


        public IActionResult Update([FromRoute] int id)
        {
            var result = billService.GetById(id);
            var billDTO = mapper.Map<Bill, BillDTO>(result.Data);
            return View(billDTO);
        }

        [HttpPost]
        public IActionResult Update([FromForm] BillDTO billDTO)
        {
            if (ModelState.IsValid)
            {
                var result = billService.Update(billDTO);
                TempData["message"] = result.Message;
                return RedirectToAction("Index");
            }
            return View(billDTO);

        }

        public DataResult<int> GetApartmentComplexIdViaClaims()
        {
            try
            {
                int apartmentComplexId = int.Parse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value);
                return new DataResult<int>(true, "Complex Id fetched succesfully", apartmentComplexId);
            }
            catch
            {
                return new DataResult<int>(false, "Complex Id couldn't fetched", -1);
            }

        }
    }
}

AparmentBillManagementMVC/Controllers/TenantController.cs
using Bussiness.Abstract;
using Core.Utilities;
using Entity.DTOs;
using Entity.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AparmentBillManagementMVC.Controllers
{
    [Authorize(Roles = "manager")]
    public class TenantController : Controller
    {
        private readonly ITenantService tenantService;

        public TenantController(ITenantService tenantService)
        {
            this.tenantService = tenantService;
        }

        public IActionResult Index()
        {
            var idResult = GetApartmentComplexIdViaClaims();
            if (idResult.Success == false)
            {
                TempData["message"] = "Something went wrong. Please re login to website.";
                return View(new List<TenantVM>());
            }

            var model = tenantService.GetTenantVMs(apartmentComplexId: idResult.Data).Data;
            return View(model);
        }

        public IActionResult Tenant([FromQuery] int apartmentId)
        {
            TenantDTO tenantDTO = new TenantDTO();
            tenantDTO.ApartmentId = apartmentId;
            return View(tenantDTO);
        }

        [HttpPost]
        public IActionResult Tenant([FromForm] TenantDTO tenantDTO)
        {

            if (ModelState.IsValid)
            {
                var result = tenantService.Add(tenantDTO);
                TempData["message"] = result.Message;
                if (result.Success)
                {
                    return RedirectToAction("Index");
                }

            }
            return View(tenantDTO);
        }

        public IActionResult Delete(int id)
        {
            var result = tenantService.DeleteById(id);
            TempData["message"] = result.Message;
            return RedirectToAction("Index");
        }

        public IActionResult Update([FromRoute] int id)
        {
            var model = tenantService.GetAsDTOById(id);
            if (model == null)
            {
                TempData["message"] = model.Message;
            }
            return View(model.Data);
        }

        [HttpPost]
        public IActionResult Update(TenantDTO tenantDTO)
        {
            if (ModelState.IsValid)
            {
                var result = tenantService.Update(tenantDTO);
                TempData["message"] = result.Message;
                if (result.Success)
                    return RedirectToAction("Index");
            }
            return View(tenantDTO);
        }

        [HttpPost]
        public PartialViewResult TenantsList(string? blockName, string? nameFilter, bool onlyHasDebt)
        {
            var idResult = GetApartmentComplexIdViaClaims();
            if (idResult.Success == false)
            {
                TempData["message"] = "Something went wrong. Please re login to website.";
                return PartialView(new List<TenantVM>());
            }

            if (blockName == "all")
            {
                blockName = null;
            }
            var model = tenantService.GetTenantVMs(idResult.Data, blockName, nameFilter, onlyHasDebt);
            return PartialView(model.Data);
        }

        public DataResult<int> GetApartmentComplexIdViaClaims()
        {
            try
            {
                int apartmentComplexId = int.Parse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value);
                return new DataResult<int>(true, "Complex Id fetched succesfully", apartmentComplexId);
            }
            catch
            {
                return new DataResult<int>(false, "Complex Id couldn't fetched", -1);
            }

        }
    }
}

AparmentBillManagementMVC/Views/Shared/ApartmentsList.cshtml
@model List<ApartmentVM>

<style>
    .rotate {
        transform: rotate(90deg);
        /* Safari */
        -webkit-transform: rotate(90deg);
        /* Firefox */
        -moz-transform: rotate(90deg);
        /* IE */
        -ms-transform: rotate(90deg);
        /* Opera */
        -o-transform: rotate(90deg);
        /* Internet Explorer */
        filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
        position: absolute;
        right: 0;
        bottom: 40px;
    }
</style>

<div class="row justify-content-center">

    @foreach (ApartmentVM item in Model)
    {

        <div class="card my-3 mx-3 col-3 col-md-6 col-lg-4 col-sm-12 apartmentCard" style="width: 18rem;">
            <div class="card-body d-flex flex-column justify-content-between">
                <div>
                    <h2 class="card-title">@item.Apartment.BlockName - @item.Apartment.Number</h2>
                    @if (String.IsNullOrEmpty(item.TenantName) == false)
                    {
                        <h6 class="card-subtitle mb-2 text-muted">@item.TenantName</h6>
                    }
                    else
                    {
                        <div class="d-flex justify-content-between align-items-baseline">
                            <h6 class="card-subtitle mb-2 text-success ">No Tenant</h6>
                            <a class="btn btn-outline-success  p-1" asp-controller="Tenant" asp-action="Tenant" asp-route-apartmentId="@item.Apartment.Id"><i class="fa fa-plus"></i> Add Tenant</a>
                        </div>
                    }
                    <p>Floor:  @item.Apartment.Floor</p>
                    <p>Type:  @item.Apartment.Type.ToString()</p>
                    @if (item.DebtAmount > 0)
                    {
                        <p>Debt:  <big class="card-text text-danger">@string.Format("{0:C}",item.DebtAmount)</big></p>
                    }
                    else if (item.DebtAmount == 0)
                    {
                        <p>Debt:  <big class="card-text text-success">@string.Format("{0:C}",item.DebtAmount)</big></p>
                    }

                </div>
                <div style="margin-right:40px; bottom:20px">
                    <a class="btn btn-danger mb-3 w-100" asp-controller="Apartment" asp-action="Delete" asp-route-id="@item.Apartment.Id">
                        <i class="fa fa-trash"></i>  Delete Apartment
                    </a>
                    <a class="btn btn-warning text-white w-100" asp-controller="Apartment" asp-action="Update" asp-route-id="@item.Apartment.Id">
                        <i class="fa fa-pencil"></i>  Update Apartment
                    </a>
                    @if (String.IsNullOrEmpty(item.TenantName) == false)
                    {
                        <a class="btn btn-outline-info rotate" asp-controller="Bill" asp-action="Bill" asp-route-apartmentId="@item.Apartment.Id" asp-route-tenantName="@item.TenantName">Add Bill</a>
                    }
                    else
                    {
                        <a class="btn btn-outline-info rotate" onclick="addBillAlert()">Add Bill</a>
                    }

                </div>
            </div>
        </div>
    }

</div>

AparmentBillManagementMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aparment Bill Management MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome-4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AparmentBillManagementMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/sweetalert2-11.10.1/dist/sweetalert2.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Apartment" asp-action="Index">Home</a>


                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Tenant" asp-action="Index">Tenants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bill" asp-action="Index">Bills</a>
                        </li>

                    </ul>
                    <div class="nav-item" style="margin-right:20px;">
                        <a class="btn btn-outline-primary px-1 border-0 px-0" asp-area="" asp-action="Index" asp-controller="Message" asp-route-tenantId="null" class="">
                            <i class="position-relative fa fa-envelope" style="margin-right:7px;">
                                <span id="unreadMessagesCount" class="p-1 mx-1 position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning visually-hidden">+9</span>
                        </i> Messages </a>
                    </div>
                    <div class="nav-item">

                        <a class="btn btn-outline-primary border-0 px-1" asp-action="Logout" asp-controller="Auth">
                        <i class="fa fa-sign-out"></i>
                        </a>
                    </div>
                </div>

              
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert2-11.10.1/dist/sweetalert2.all.min.js"></script>
    <script src="~/lib/notify.min.js"></script>

    <script>
        function GetTotalUnreadMessageCount() {
            $.get("/Auth/IsAuthenticated", function (data) {
                if (data == false) {
                    console.log("Not authenticated");
                    return;
                }
                $.get("/Message/GetTotalUnreadMessageCount", function (data) {
                    console.log("GetTotalUnreadMessageCount: " + data);
                    if (data > 0) {
                        $("#unreadMessagesCount").text(data);
                        $("#unreadMessagesCount").removeClass("visually-hidden");
                    }
                    else {
                        $("#unreadMessagesCount").addClass("visually-hidden");
                    }

                });
            });


        }
$(document).ready(function () {
GetTotalUnreadMessageCount();
    setInterval(GetTotalUnreadMessageCount, 8000);
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>